
name: Build LaTeX document
on:
  push:
    branches:
      - main
env:
  AWS_REGION: eu-central-1
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv_en.tex
            cv_de.tex
      - name: Upload
        run: |
          aws s3 cp \
          --acl public-read \
          *.pdf \
          s3://www.iablokov.dev
